import os

_MODULE_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_DIR = os.path.dirname(_MODULE_DIR)

CAMERA_ID = 0
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_FPS = 30

YOLO_MODEL = os.path.join(_PROJECT_DIR, "models", "yolo11n.pt")
YOLO_CONFIDENCE = 0.4
YOLO_DEVICE = "cpu"
YOLO_IMGSZ = 320

DETECTION_INTERVAL = 0.15
DETECT_SCALE = 0.25
RISK_COOLDOWN = 5.0

FIRE_AREA_MIN = 250
FIRE_CONFIDENCE_THRESHOLD = 0.40
FIRE_STOVE_ZONE_ONLY = True
FIRE_COVERAGE_LOW = 0.03
FIRE_COVERAGE_MEDIUM = 0.08
FIRE_COVERAGE_HIGH = 0.15
FIRE_HISTORY_FRAMES = 6
FIRE_SHAPE_MIN = 1.8
FIRE_FLICKER_FRAMES = 10

SMOKE_AREA_MIN = 250
SMOKE_HISTORY_FRAMES = 3
SMOKE_COVERAGE_MIN = 0.001
SMOKE_EDGE_MAX = 0.35
SMOKE_EDGE_MIN = 0.0
SMOKE_SHAPE_MAX = 3.0
SMOKE_FLICKER_FRAMES = 6
SMOKE_TEXTURE_MIN = 1.0
SMOKE_TEXTURE_MAX = 30.0
SMOKE_CONFIDENCE_THRESHOLD = 0.40
SMOKE_STOVE_ZONE_ONLY = True

PERSON_HYSTERESIS_SECONDS = 5
UNATTENDED_WARN_MINUTES = 1
UNATTENDED_WARN_HIGH_MINUTES = 30
UNATTENDED_ALARM_MINUTES = 40

STOVE_ZONE = {"x": 0.25, "y": 0.35, "w": 0.50, "h": 0.45}

EVENT_LOG_FILE = os.path.join(_PROJECT_DIR, "logs", "eventos.log")
ALARM_SOUND_FILE = os.path.join(_PROJECT_DIR, "data", "alarm.wav")
