import os

_MODULE_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_DIR = os.path.dirname(_MODULE_DIR)

CAMERA_ID = 0
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_FPS = 30

YOLO_MODEL = os.path.join(_PROJECT_DIR, "models", "yolo11n.pt")
YOLO_CONFIDENCE = 0.4
YOLO_DEVICE = "cpu"

DETECTION_INTERVAL = 0.15
RISK_COOLDOWN = 5.0

FIRE_AREA_MIN = 300
FIRE_COVERAGE_LOW = 0.02
FIRE_COVERAGE_MEDIUM = 0.08
FIRE_COVERAGE_HIGH = 0.15
FIRE_MOVEMENT_MIN = 3
FIRE_HISTORY_FRAMES = 5

SMOKE_AREA_MIN = 500
SMOKE_HISTORY_FRAMES = 5

PERSON_HYSTERESIS_SECONDS = 5
UNATTENDED_WARN_MINUTES = 1
UNATTENDED_WARN_HIGH_MINUTES = 30
UNATTENDED_ALARM_MINUTES = 40

STOVE_ZONE = {"x": 0.15, "y": 0.35, "w": 0.70, "h": 0.55}

EVENT_LOG_FILE = os.path.join(_PROJECT_DIR, "eventos.log")
ALARM_SOUND_FILE = os.path.join(_PROJECT_DIR, "data", "alarm.wav")
